### ISSUE TITLE
Cloud-based test services (BrowserStack, Sauce Labs) seem unsupported. Are integrations planned for the future?

### ISSUE THREAD

**Issue by flntzr** [telekom/testerra#187]
Hey team, I am currently evaluating Testerra for future projects. 
It looks promising so far, thank you for the work! 

For testing large projects, cloud-based test services such as BrowserStack and Sauce Labs can be hugely helpful. Looking through their supported integrations, I cannot find Testerra directly, though each service supports both Selenium and Appium as some of Testerra's underlying tech[1][2].

I assume that doesn't magically mean these cloud services support Testerra. 

Are there currently plans to add Testerra integrations for one or both of these services in the future?

[1] [https://www.browserstack.com/docs/](https://www.browserstack.com/docs/)
[2] [https://docs.saucelabs.com/ ](https://docs.saucelabs.com/)

**Comment by martingrossmann** [comment]
Hi,

in generally there is no need to create special integrations for platforms like Saucelabs or Browserstack. Testerra is based on Selenium so every Selenium based service should work. All needed platform configurations can handled by browser capabilities.

For Saucelabs you have to add some caps and configs like described here: https://docs.saucelabs.com/web-apps/automated-testing/selenium/.

Based on https://github.com/telekom/testerra-skeleton the following changes are needed:

````
# test.properties
tt.selenium.server.url=https://ondemand.us-west-1.saucelabs.com/wd/hub
````

````java
    // class AbstractTest

    @BeforeSuite
    public void configureChromeOptions() {

        WebDriverManager.setUserAgentConfig(Browsers.chrome, new ChromeConfig() {
            @Override
            public void configure(ChromeOptions options) {
                Map<String, Object> sauceOptions = new HashMap<>();
                sauceOptions.put("username", "your-username");
                sauceOptions.put("accessKey", "your-access-key");
                sauceOptions.put("name", "Your test name");
                options.setCapability("sauce:options", sauceOptions);

                options.setCapability("platformName", "Windows 10");
                options.setCapability("browserVersion", "92");
            }
        });
    }
````

Please note that Saucelabs uses `browserVersion` instead of `version` as cabability. So Testerra property `tt.version` does not work.

If you need a proxy like in a company environment you have to deactivate `WebDriverManager.setGlobalExtraCapability(CapabilityType.PROXY, proxy);` in `AbstractTest` for Saucelabs.

**Comment by mreiche** [comment]
The BrowserStack configuration is easier:

You just need to setup your Selenium host URL in `test.properties` like this:

```properties
tt.selenium.server.url=https://USERNAME:AUTOMATE_KEY@hub-cloud.browserstack.com/wd/hub
tt.webdriver.mode=remote
```

or programatically within your test
```java
@Test
public void test_browserStack() throws MalformedURLException {
    final String USERNAME = "";
    final String AUTOMATE_KEY = "";
    final String URL = "https://" + USERNAME + ":" + AUTOMATE_KEY + "@hub-cloud.browserstack.com/wd/hub";
    DesktopWebDriverRequest desktopWebDriverRequest = new DesktopWebDriverRequest();
    desktopWebDriverRequest.setSeleniumServerUrl(URL);
    desktopWebDriverRequest.setWebDriverMode(WebDriverMode.remote);

    WebDriver webDriver = WebDriverManager.getWebDriver(desktopWebDriverRequest);
    webDriver.get("https://www.google.com");
    Assert.assertEquals(webDriver.getTitle(), "Google");
}
```

**Comment by flntzr** [comment]
Thank you both for the detailed answers, you have been very helpful 🙂
