### ISSUE TITLE
Make UiElement unique

### ISSUE THREAD

**Issue by mreiche** [telekom/testerra#39]
We've got a feature request about changing the default behaviour of Testerra internals:

# Current behaviour
* Per default, the `GuiElement/UiElement` contains a relation of elements (0..n)
* It points only to the first `WebElement` when performing an action
* This was a design decision made long time ago without a explanation
* When you want to get more elements, you need to use the list feature `getList()/list()`

## Pros
* More robust in some cases when a selector returns multiple elements

## Cons
* Counter intuitive list API
* People expect only one element
* Error proness in some cases

# Desired behaviour
* Element results are unique by default
* An `ElementNotFoundException` is thrown, when the result is NOT unique
* When you expect to find more elements, use the API

# Solution

## For Testerra 1
* We provide a property like `tt.uielement.find.unique` which is `false` by default.
* When `true`, all `Locate` are unique

## For Testerra 2
* According to `find()` methods, we provide addtional `findMany()`
* The `UiElement.list()` and `GuiElement.getList()` methods get deprecated

## For Testerra X
* Make `tt.uielement.find.unique` default `true`
* Remove that property

Discussion: What do you think about this design change? @martingrossmann @mbeuthan @erickubenka @gogro ?

**Comment by martingrossmann** [comment]
The default behaviour to return the first element in case of multiple elements was taken from Selenium. The Selenium `find()` has the same behaviour 
See also https://www.guru99.com/find-element-selenium.html and https://github.com/SeleniumHQ/selenium/blob/a22d0fd220abf69e7ad32100f6f60a426dfba9c6/java/client/src/org/openqa/selenium/WebElement.java#L250

Therefor the _default_ setting for Testerra `find()` cannot differ from Selenium. A Selenium user expects the same result until the default Selenium setting will change.

Of course we can provide some additional information to the user. But an `ElementNotFoundException` should not the correct way because there _is_ an element available. This exception should only used if an element is not part of the page.

**Comment by martingrossmann** [comment]
And as an additional information: The `find` behaviour is W3C standard: https://w3c.github.io/webdriver/#find-element-from-element

**Comment by mreiche** [comment]
But even this is the default Selenium behaviour, isn't it useful to have a option `tt.uielement.find.unique=true`?

**Comment by martingrossmann** [comment]
Well, we can add an option like this how _strict_ is the `find` method of Testerra:
* `strict_mode=selenium` --> default Selenium behaviour (=default setting)
* `strict_mode=warning` --> A warning is shown in the log/report, the behaviour is the same like Selenium
* `strict_mode=unique` --> A `MultipleElementFoundException` occurs in case of multiple elements were found

**Comment by martingrossmann** [comment]
But I'm not sure why we really need this setting. A `unique` or `strict` mode supports to find unclear Xpath definitions. But a user should already declare a unique Xpath during implementation, not later.

**Comment by mreiche** [comment]
Another approach could be a general `Locate` interceptor like:

```java
Locate.setLocatorConfigurator(locator -> {
  locator.displayed();
  locator.unique();
});
```

**Comment by martingrossmann** [comment]
But with this you give Testerra the responsibility to find the correct element, not the user. IMHO this is not deterministic any more. The display attribute can change during execution. so Testerra selects another element.

**Comment by mreiche** [comment]
With the `setLocatorConfiguration` you just setup a default configuration for locators, like `setUserAgentConfig` does.
